config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :answers
      resources :equipment
      resources :questions

      root to: 'users#index'
    end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :answers, except: %i[show new]
  resources :equipment, except: :show
  resources :questions, except: :show do
    get 'summary', as: 'summary'
  end

  resources :users, except: :show

  root to: 'home#index', as: 'home'

  get 'summary', as: 'summary', controller: :answers, action: :index
  put 'validate', as: 'validate', controller: :users
  get 'profile', as: 'profile', controller: :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  enum answer_type: %i[text numerical choice]
  serialize :choices, Array
  has_many :answers, dependent: :destroy
  validates :question, presence: true
  validates :answer_type, presence: true
  validates :choices, presence: true, if: :test

  def test
    choice?
  end
end

app/controllers/admin/questions_controller.rb
module Admin
  class QuestionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement
    # custom behavior
    # For example, you may want to send an email after a foo is updated.

    def resource_params
      params[:question][:choices] = params[:question][:choices].split(',')
      params.require(resource_name).permit(
        *dashboard.permitted_attributes,
        choices: []
      )
    end

    # def update
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.

    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.

    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[edit create update destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/new
  def new
    if policy(:application).show?
      redirect_to questions_url(open: true)
    else
      redirect_to questions_url, notice: 'Access denied.'
    end
  end

  # GET /questions/1/edit
  def edit
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.js
    end
  end

  # POST /questions
  # POST /questions.json
  def create
    if params[:method].eql?('put')
      update
    else
      @question = Question.new(question_params)

      respond_to do |format|
        if @question.save
          format.html { redirect_to questions_url, notice: 'Question added.' }
        else
          format.html { render :new }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        Answer.where(question_id: @question.id).destroy_all
        format.html { redirect_to questions_url, notice: 'Question edited.' }
      else
        format.json {
          render json: @question.errors,
          status: :unprocessable_entity
        }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question deleted.' }
      format.json { head :no_content }
    end
  end

  # GET /questions/summary
  def summary
    @question = Question.find(params[:question_id])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to questions_url, notice: 'Record not found.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id]) if params[:id]
  rescue ActiveRecord::RecordNotFound
    redirect_to questions_url, notice: 'Record not found.'
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def question_params
    params.permit(:id, :question, :answer_type, :show_in_list, choices: [])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def questions(user_id, answered)
    return unless user_id
    answered_questions = get_answered(user_id)
    case answered
    when true
      @questions = Question.where(id: answered_questions).order(:id)
        .page(params[:page_a]).per(3)
    when false
      @questions = Question.where.not(id: answered_questions).order(:id)
        .page(params[:page_u]).per(3)
    when nil
      @questions = Question.order(:id).page(params[:page]).per(3)
    end
  end

  def get_answered(user_id)
    Answer.where(user_id: user_id).pluck(:question_id)
  end

  def get_answer(question_id)
    Answer.find_by(question_id: question_id, user_id: current_user.id)
  end
end

app/views/questions/_admin.html.erb
<% cache questions do %>
  <% questions.each do |question| %>
    <% cache question do %>
    <div class="w-50 mx-auto card" id="question-card">
      <div class="card-header">
        <h4 class="card-title"><%= question.question %></h4>
      </div>
      <div class="card-body">
        <div>
          <h5>
            <%= t('.answer_type') %> : 
            <span class="badge badge-pill badge-info">
              &nbsp;
              <%= question.answer_type %>
              &nbsp;
            </span>
          </h5>
          <h5>
            <%= t('.shown_in_list') %> : 
            <span class="badge badge-pill badge-info">
              &nbsp;
              <%= question.show_in_list ? "Yes" : "No" %>
              &nbsp;
            </span>
          </h5>
          <% if question.choice? %>
            <h5>
              <%= t('.choices') %> : 
              <% question.choices.each do |choice| %>
                <span class="badge badge-pill badge-secondary">
                  &nbsp;
                    <%= choice %>
                  &nbsp;
                </span>
              <% end %>
            </h5>
          <% end %>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to t('.show_answers') , question_summary_path(question.id), :class => "btn btn-warning" %>
          <%= link_to  t('edit'), edit_question_path(question.id), :class => "btn btn-primary", remote: true%>
          <%= link_to t('remove') , question_path(question.id), :method => :delete, :class => "btn btn-danger", :data => {:confirm => "Remove this question?"}, remote: true %>
        </div>
      </div>
      <div class="card-footer text-muted" >
        <small><%= question.created_at %></small>
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/questions/_edit-answer.html.erb
<%= react_component("QuestionForm",types: Question.answer_types, question: @question, auth_token: form_authenticity_token) %>
<script>
  ReactRailsUJS.mountComponents()
</script>

app/views/questions/_edit.html.erb
<%= react_component("QuestionForm",types: Question.answer_types, question: @question, auth_token: form_authenticity_token) %>
<script>
  ReactRailsUJS.mountComponents()
</script>

app/views/questions/_form.html.erb
<%= react_component("QuestionForm", types: Question.answer_types, auth_token: form_authenticity_token ) %>

app/views/questions/_question.html.erb
<% questions.each do |question| %>
  <div class="w-50 mx-auto card" id="question-card">
    <div class="card-header">
      <h4 class="card-title"><%= t('.question') %></h4>
    </div>
    <div class="card-body">
      <p class="card-text"><%= question.question %></p>
      <% if not get_answered(current_user.id).include? question.id%>
        <%= form_with model: Answer.new do |f| %>
          <div class="form-row">
            <div class="form-group col-md-6">
              <% case question.answer_type %>
              <% when 'text' %>
                <%= f.text_field :answer, type:"text", class:"form-control", placeholder: "Enter Answer", required: true, maxlength: 50 %>
              <% when 'numerical' %>
                <%= f.text_field :answer, type:"number", class:"form-control", required: true %>
              <% when 'choice' %>
                <%= f.select(:answer, question.choices.map {|key, value|  [key.titleize,key] }, { include_blank: 'Choose...' }, { class: "selectpicker form-control", required: true }) %>
              <% end %>
              
              <%= f.text_field :question_id, type:"hidden", value: question.id %>
              <%= f.text_field :user_id, type:"hidden", value: current_user.id %>
            </div>
            <div class="form-group col-md-2">
              <%= f.submit t('submit'), class:"btn btn-primary"%>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="btn-group dropright" id="question-options">
          <button type="button"  class="btn btn-light" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            :
          </button>
          <div class="dropdown-menu">
            <%= link_to t('edit') , edit_answer_path(get_answer(question.id).id), :class => "dropdown-item", remote: true%>
            <%= link_to t('remove') , answer_path(get_answer(question.id).id), :method => :delete, :class => "dropdown-item", :data => {:confirm => "Remove this answer?"}, remote: true %>
          </div>
        </div>
        <div>
          <h5>
            You : 
            <span class="badge badge-info">
              &nbsp;
              <%= get_answer(question.id).answer %>
              &nbsp;
            </span>
          </h5>
        </div>
      <% end %>
    </div>
    <div class="card-footer text-muted" >
      <small><%= question.updated_at.localtime %></small>
    </div>
  </div>
<% end %>

app/views/questions/edit.js.erb
$("#edit-question-content").html("<%= j render 'edit-answer' %>");
$('#editQuestion').modal('show');

app/views/questions/edit_answer.js.erb
$("#edit-answer-content").html("<%= j render 'answers/form', answer: @answer %>");
$('#editAnswer').modal('show');

app/views/questions/index.html.erb
<% if policy(:application).show? %>
  <div class="button-container">
    <button type="button" class="btn btn-outline-primary btn-lg w-25 mx-auto" data-toggle="modal" data-target="#addQuestion"><%= t('.add_question')%></button> 
  </div>
  <div class="questions-admin-div">
    <%= render partial: "admin", locals: { questions: questions(current_user.id, answered = nil) }%>
  </div>
  <% if questions(current_user.id, answered = nil).length > 0 %>
    <div class="paginator-admin">
      <%= paginate questions(current_user.id, answered = nil), :remote => true %>
    </div>
  <% else %>
    <h3 class="text-muted"> 
      <p class="text-center">
        <%= t('empty') %>.
      </p>
    </h3>
  <% end %>
<% else %>
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-unanswered-tab" data-toggle="tab" href="#nav-unanswered" role="tab" aria-controls="nav-unanswered" aria-selected="true"><%= t('.unanswered') %></a>
    <a class="nav-item nav-link" id="nav-answered-tab" data-toggle="tab" href="#nav-answered" role="tab" aria-controls="nav-answered" aria-selected="false"><%= t('.answered') %></a>
  </div>
</nav>

<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-unanswered" role="tabpanel" aria-labelledby="nav-unanswered-tab">
    <div class="questions-unanswered-div">
      <%= render partial: 'question', locals: {questions: questions(current_user.id, answered = false), user_id: current_user.id} %>
    </div> 
    <% if questions(current_user.id, answered = false).length > 0 %>
      <div class="paginator-unanswered">
        <%= paginate questions(current_user.id, answered = false), :remote => true, :param_name => 'page_u' %>
      </div>
    <% else %>
      <h3 class="text-muted"> 
        <p class="text-center">
          <%= t('empty') %>.
        </p>
      </h3>
    <% end %>
  </div>

  <div class="tab-pane fade" id="nav-answered" role="tabpanel" aria-labelledby="nav-answered-tab">
    <div class="questions-answered-div">
      <%= render partial: 'question', locals: {questions: questions(current_user.id, answered = true), user_id: current_user.id} %>
    </div> 
    <% if questions(current_user.id, answered = true).length > 0 %>
      <div class="paginator-answered">
        <%= paginate questions(current_user.id, answered = true), :remote => true, :param_name => 'page_a' %>
      </div>
    <% else %>
      <h3 class="text-muted"> 
        <p class="text-center">
          <%= t('empty') %>.
        </p>
      </h3>
    <% end %>
  </div>
</div>

<%end%>

<div class="modal" id="addQuestion" tabindex="-1" role="dialog" aria-labelledby="add-question-modal-label" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t('.add_question')%></h5>
      </div>
      <%= render 'form', question: Question.new %>
    </div>
  </div>
</div>

<div class="modal fade" id="editQuestion" tabindex="-1" role="dialog" aria-labelledby="editQuestionTitle" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= t('.edit_question')%>
        </h5>
      </div>
      <div id="edit-question-content"></div>
    </div>
  </div>
</div>

<div class="modal fade" id="editAnswer" tabindex="-1" role="dialog" aria-labelledby="editAnswerTitle" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= t('.edit_answer')%>
        </h5>
      </div>
      <div id="edit-answer-content"></div>
    </div>
  </div>
</div>

app/views/questions/index.js.erb
$('.questions-unanswered-div').html('<%= escape_javascript render(partial: "question", locals: {questions: questions(current_user.id, answered = false)}) %>');
$('.questions-answered-div').html('<%= escape_javascript render(partial: "question", locals: {questions: questions(current_user.id, answered = true)}) %>');
$('.questions-admin-div').html('<%= escape_javascript render(partial: "admin", locals: {questions: questions(current_user.id, answered = nil)}) %>');

$('.paginator-unanswered').html("<%= escape_javascript(paginate(questions(current_user.id, answered = false), :remote => true, :param_name => 'page_u').to_s) %>");
$('.paginator-answered').html("<%= escape_javascript(paginate(questions(current_user.id, answered = true), :remote => true, :param_name => 'page_a').to_s) %>");
$('.paginator-admin').html('<%= escape_javascript(paginate(questions(current_user.id, answered = nil), :remote => true).to_s) %>');

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Answer type:</strong>
  <%= @question.answer_type %>
</p>

<p>
  <strong>Show in list:</strong>
  <%= @question.show_in_list %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/questions/summary.html.erb
<div class="modal-header">
  <h2><%= t('.answers')%> to "<%= @question.question %>"</h2>
</div>

<div class="modal-body">
  <% if @question.answers.empty? %>
    <h3 class="text-muted"> 
      <p class="text-center">
        <%= t('empty') %>.
      </p>
    </h3>
  <% else %>
    <table class="table table-striped table-hover">
      <thead>
        <tr class="table-info">
          <th scope="col">Name</th>
          <th scope="col">Answer</th>
          <th scope="col">Date Answered</th>
        </tr>
      </thead>
      <% @question.answers.each do |answer| %>
        <tr>
          <th scope="row"><%= image_tag get_user(answer.user_id).picture.url(:thumb) %> <%= get_user(answer.user_id).name %></th>
          <td><%= answer.answer %></td>
          <td><%= answer.updated_at.localtime %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

<div class="modal-footer">
  <%= link_to  "Back", :back, class: "btn btn-secondary" %>
</div>