config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :answers
      resources :equipment
      resources :questions

      root to: 'users#index'
    end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :answers, except: %i[show new]
  resources :equipment, except: :show
  resources :questions, except: :show do
    get 'summary', as: 'summary'
  end

  resources :users, except: :show

  root to: 'home#index', as: 'home'

  get 'summary', as: 'summary', controller: :answers, action: :index
  put 'validate', as: 'validate', controller: :users
  get 'profile', as: 'profile', controller: :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  enum status: %i[deployed stored defective]
  enum equipment_type: %i[hardware license online\ account peripheral]
  belongs_to :user
  validates :name, presence: true
  validates :equipment_type, presence: true
  validates :status, presence: true
  validates :serial_number, format: { with: /\A^([\d+]{3}[-]){2}[\d+]{3}$\Z/,
    allow_blank: true }
end

app/controllers/admin/equipment_controller.rb
module Admin
  class EquipmentController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement
    # custom behavior
    # For example, you may want to send an email after a foo is updated.

    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.

    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.

    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :authenticate_user!
  before_action :set_equipment, only: %i[edit update destroy]
  before_action :license_check, only: %i[create update]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/new
  def new
    if policy(:application).show?
      redirect_to equipment_index_url(
        open: true, page: helpers.getter_equipment.total_pages
      )
    else
      redirect_to equipment_index_url, notice: 'Access denied.'
    end
  end

  # GET /equipment/1/edit
  def edit
    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.js
    end
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)
    respond_to do |format|
      if @equipment.save
        format.html do
          redirect_to equipment_index_url,
            notice: 'Equipment added.'
        end
      else
        format.html { render :new }
        format.json do
          render json: @equipment.errors,
          status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html do
          redirect_to equipment_index_url,
            notice: 'Equipment edited.'
        end
      else
        format.html { render :edit }
        format.json do
          render json: @equipment.errors,
          status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html do
        redirect_to equipment_index_url,
          notice: 'Equipment deleted.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_equipment
    @equipment = Equipment.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    redirect_to equipment_index_url, notice: 'Record not found.'
  end

  # Never trust parameters from the scary internet, only allow the white
  # list through.
  def equipment_params
    params.require(:equipment).permit(
      :name, :equipment_type, :status, :user_id, :serial_number)
  end

  def license_check
    params[:equipment].delete :serial_number unless
      params[:equipment][:equipment_type].eql?('license')
  end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
  def getter_equipment
    @equipment =
    if policy(:application).show?
      Equipment.order(:id).page(params[:page]).per(12)
    else
      current_user.equipment.order(:id).page(params[:page]).per(12)
    end
  end

  def get_equipment_status_report(type)
    @equipment = Equipment.select(:status).group(:status).count(:status)
    if type.eql?('pie')
      @equipment.each do |key, value|
        @equipment[key] = ((value.to_f / Equipment.all.count.to_f) * 100)
          .round(2)
      end
    end
    @equipment
  end

  def get_equipment_type_report(type)
    @equipment = Equipment.select(:equipment_type).group(:equipment_type)
      .count(:equipment_type)
    if type.eql?('pie')
      @equipment.each do |key, value|
        @equipment[key] = ((value.to_f / Equipment.all.count.to_f) * 100)
          .round(2)
      end
    end
    @equipment
  end
end

app/views/equipment/_equipment.html.erb
<% cache equipments do%>
  <% equipments.each do |equipment| %>
    <% cache equipment do%>
  <% if equipment.equipment_type.eql? "license"%>
    <div class="card text-white bg-info m-4" id="equipment-card">
  <% else %>
    <div class="card text-white bg-info m-4" id="user-card">
  <% end %>
    <div class="card-header">
        <% if equipment.name.length > 26 %>
          <a data-toggle="tooltip" data-placement="top" title='<%= equipment.name %>' >
            <%= equipment.name[0,24]+"..." %>
          </a>
        <% else %>
          <%= equipment.name %>
        <% end%>
        <% if current_user.role.eql? "admin" #admin %>
          <div class="btn-group dropright" id="options">
            <button type="button"  class="btn btn-outline-info btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white;">
              :
            </button>
            <div class="dropdown-menu" >
              <%= link_to t('edit') , edit_equipment_path(equipment.id), :class => "dropdown-item", remote: true%>
              <%= link_to t('remove') , equipment_path(equipment.id), :method => :delete, :class => "dropdown-item", :data => {:confirm => "Remove this equipment?"}, remote: true %>
            </div>
          </div>
        <% end %>
      </div> 
      <div class="card-body">
        <% if current_user.role.eql? "admin" #admin %>
        <h4>
          <%= t('.owner') %> : 
          <span class="badge badge-pill badge-dark">
            &nbsp;
            <% if get_user(equipment.user_id).name.length > 10 %>
              <a data-toggle="tooltip" data-placement="top" title='<%= get_user(equipment.user_id).name %>' >
                <%= get_user(equipment.user_id).name[0,8]+"..." %>
              </a>
            <% else %>
              <%= get_user(equipment.user_id).name %>
            <% end %>
            &nbsp;
          </span>
        </h4>
        <% end %>
        <h4>
          <%= t('.type') %> : 
          <span class="badge badge-pill badge-light">
            &nbsp;
            <%= equipment.equipment_type.titleize %>
            &nbsp;
          </span>
        </h4>
        <h4>
          <%= t('.status') %> : 
          <span class="badge badge-pill badge-dark">
            &nbsp;
            <%= equipment.status.titleize %>
            &nbsp;
          </span>
        </h4>
        <% if equipment.equipment_type.eql? "license"%>
          <h4>
            <%= t('.serial_number') %> : 
            <span class="badge badge-pill badge-dark">
              &nbsp;
              <%= equipment.serial_number %>
              &nbsp;
            </span>
          </h4>
        <% end %>
      </div>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/equipment/_form.html.erb
<%= form_with model: equipment, id: "test" do |f| %>
<div class="modal-body">
    <div class="form-group">
      <%= f.label :name %>: 
      <%= f.text_field :name, type:"text", class:"form-control", id: "name", required: true, maxlength: 50 %>
    </div> 
    <div class="form-group">
      <%= f.label :equipment_type %>: 
      <%= f.select(:equipment_type, Equipment.equipment_types.map {|key, value|  [key.titleize,key] }, { include_blank: 'Choose...' }, { class: "selectpicker form-control type", required: true }) %>
    </div>
    <div class="form-group" id="serial">
      <%= f.label :serial_number %>: 
      <%= f.text_field :serial_number, type:"text", class:"form-control", raria: { "describedby" => "serialHelp" }, pattern: "(([0-9]{3}[-]){2}[0-9]{3})", required: true, maxlength: 11 %>
      <small id="serialHelp" >Please follow the format XXX-XXX-XXX.</small>
    </div>
    <div class="form-group">
      <%= f.label :status %>: 
      <%= f.select(:status, Equipment.statuses.map {|key, value|  [key.titleize,key] }, { include_blank: 'Choose...' }, { class: "selectpicker form-control", required: true }) %>
    </div>
    <div class="form-group">
      <label for="user">Assigned User</label>: 
      <%= f.select(:user_id, User.select(:id, :name).where.not(role: 1).map {|user|  [user.name,user.id] }, { include_blank: 'Choose...' } , { class: "selectpicker form-control", "data-dropup-auto" => false, "data-live-search" => true, id:"user", required: true } ) %>
    </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" id="close" data-dismiss="modal"><%= t('close') %></button>
  <%= f.submit t('submit'), class:"btn btn-primary"%>
</div>
<% end %>

app/views/equipment/_report.html.erb
<h1 class="text-center">Distribution</h1>
<div class="report-container" >
  <div>
    <h2 class="report-title">Equipment Status</h2>
    <%= pie_chart get_equipment_status_report("pie"), donut: true, suffix: "%", colors: ["#5bc0de", "#5cb85c", "#f0ad4e", "#d9534f", "#0275d8", "#292b2c"].shuffle %>
  </div>
  <div>
    <h2 class="report-title">Equipment Type</h2>
    <%= pie_chart get_equipment_type_report("pie"), donut: true, suffix: "%", colors: ["#5bc0de", "#5cb85c", "#f0ad4e", "#d9534f", "#0275d8", "#292b2c"].shuffle %>
  </div>
</div>
<h1 class="text-center">Totals</h1>
<div class="report-container" >
  <div>
    <h2 class="report-title">Equipment Status</h2>
    <%= column_chart get_equipment_status_report("bar"), height: "20rem", colors: ["#5bc0de", "#5cb85c", "#f0ad4e", "#d9534f", "#0275d8", "#292b2c"].shuffle%>
  </div>
  <div>
    <h2 class="report-title">Equipment Type</h2>
    <%= column_chart get_equipment_type_report("bar"), height: "20rem", colors: ["#5bc0de", "#5cb85c", "#f0ad4e", "#d9534f", "#0275d8", "#292b2c"].shuffle%>
  </div>
</div>

app/views/equipment/edit.js.erb
$("#edit-modal-content").html("<%= j render 'form', equipment: @equipment %>");
$('.selectpicker').selectpicker();
$('#editEquipment').modal('show');

app/views/equipment/index.html.erb
<% if policy(:application).show? %>
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" id="nav-equipments-tab" data-toggle="tab" href="#nav-equipments" role="tab" aria-controls="nav-equipments" aria-selected="true"><%= t('.all') %></a>
      <a class="nav-item nav-link" id="nav-report-tab" data-toggle="tab" href="#nav-report" role="tab" aria-controls="nav-report" aria-selected="false" onclick="return drawChart()"><%= t('.reports') %></a>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
<% end %>
<% if policy(:application).show? %>
  <div class="tab-pane fade show active" id="nav-equipments" role="tabpanel" aria-labelledby="nav-equipments-tab">
    <div class="button-container">
      <button type="button" class="btn btn-outline-primary btn-lg w-25 mx-auto" data-toggle="modal" data-target="#addEquipment"><%= t('.add_equipment')%></button> 
    </div>
<% else %>
    <div class="content">
<% end %>
      <div class="main-container">
        <%= render partial: "equipment", locals: { equipments: getter_equipment() } %>
      </div>
    <% if getter_equipment().length > 0 %>
      <div class="paginator">
        <%= paginate getter_equipment(), :remote => true %>
      </div>
    <% else %>
      <h3 class="text-muted"> 
        <p class="text-center">
          <%= t('empty') %>.
        </p>
      </h3>
    <% end %>
    </div>

<% if policy(:application).show? %>
    <div class="tab-pane fade" id="nav-report" role="tabpanel" aria-labelledby="nav-report-tab">
      <% if get_equipment_status_report('bar').empty? %>
        <h3 class="text-muted"> 
          <p class="text-center">
            <%= t('empty') %>.
          </p>
        </h3>
      <% else %>
        <%= render  "report" %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="modal fade" data-equipment-id="<%=current_user.id%>" id="addEquipment" tabindex="-1" role="dialog" aria-labelledby="addEquipmentTitle" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><%= t('.add_equipment') %></h5>
      </div>
        <%= render 'form', equipment: Equipment.new %>
    </div>
  </div>
</div>

<div class="modal fade" id="editEquipment" tabindex="-1" role="dialog" aria-labelledby="editEquipmentTitle" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= t('.edit_equipment')%>
        </h5>
      </div>
      <div id="edit-modal-content"></div>
    </div>
  </div>
</div>

app/views/equipment/index.js.erb
$('.main-container').html('<%= escape_javascript render(partial: "equipment", locals: {equipments: getter_equipment()}) %>');

$('.paginator').html('<%= escape_javascript(paginate(getter_equipment(), :remote => true).to_s) %>');

$('[data-toggle="tooltip"]').tooltip()

app/views/equipment/new.html.erb
<h1>New Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @equipment.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @equipment.type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @equipment.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @equipment.user %>
</p>

<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/update.js.erb
$("#addEquipment").modal('hide');