config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :answers
      resources :equipment
      resources :questions

      root to: 'users#index'
    end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :answers, except: %i[show new]
  resources :equipment, except: :show
  resources :questions, except: :show do
    get 'summary', as: 'summary'
  end

  resources :users, except: :show

  root to: 'home#index', as: 'home'

  get 'summary', as: 'summary', controller: :answers, action: :index
  put 'validate', as: 'validate', controller: :users
  get 'profile', as: 'profile', controller: :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  enum role: %i[user admin]
  has_attached_file :picture, styles: {
    medium: '150x150>', small: '50x50>', thumb: '25x25>'
  }, default_url: '/images/:style/smile.png'
  validates_attachment_content_type :picture, content_type: %r{\Aimage/.*\z}
  validates :password, confirmation: true
  validates :name, presence: true
  validates :email, uniqueness: true
  has_many :equipment, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement
    # custom behavior
    # For example, you may want to send an email after a foo is updated.

    def update
      if params[:user][:password].blank?
        params[:user].delete :password
        params[:user].delete :password_confirmation
      end
      super
    end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.

    def find_resource(param)
      User.find_by!(id: param)
    end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.

    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    redirect_to new_user_session_path unless user_signed_in?
  end

  # POST /resource
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.json { render json: { message: 'OK' }, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name role picture])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    '#'
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def sign_up(_resource_name, _resource)
    true
  end

  private

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def user_params
    params.require(:user).permit(
      :name, :role, :picture, :email, :password, :password_confirmation
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin, only: %i[index create destroy]
  before_action :set_user, only: %i[edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    redirect_to users_url(open: true)
  end

  # GET /users/1/edit
  def edit
    respond_to do |format|
      format.html { redirect_to users_url(open: false) }
      format.js
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.json { render json: { message: 'OK' }, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:user][:password].blank?
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end

    respond_to do |format|
      if @user.update(user_params)
        bypass_sign_in(@user) if  params[:user][:edit_profile].present? &&
                                  params[:user][:password].present?
        format.json { render json: { message: 'OK' }, status: :ok }
      else
        format.json {
          render json: @user.errors,
          status: :unprocessable_entity
        }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User deleted.' }
      format.json { head :no_content }
    end
  end

  # PUT /validate
  def validate
    respond_to do |format|
      case params[:type]
      when 'email'
        format.json do
                      render json: {
                        exists: User.where(email: params[:email])
                        .where.not(id: params[:id]).exists?
                      },
                      status: :ok
                    end
      when 'password'
        format.json do
                      render json: {
                        validate: User.find(params[:id])
                        .valid_password?(params[:password])
                      },
                      status: :ok
                    end
      else
        format.json do
                      render json: {
                        message: 'Bad Request'
                      },
                      status: :bad_request
                    end
      end
    end
  end

  # GET /profile
  def profile
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to users_url, notice: 'Record not found.'
  end

  # Never trust parameters from the scary internet, only allow the
  # white list through.
  def user_params
    params.require(:user).permit(
      :name, :role, :picture,
      :email, :password,
      :password_confirmation,
      :longitude, :latitude)
  end

  def authenticate_admin
    # TODO; Add authentication logic here.
    redirect_to home_path, notice: 'Access denied.' unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def getter_users
    @users = User.order(:id).page(params[:page]).per(12)
  end
end

app/views/users/_form.html.erb
<%= form_for(user, html: { multipart: true }, remote: true) do |f| %>
<div id="profile_form_alert"></div>
<div id="api_key" data=<%=ENV["API_KEY"]%>></div>
<div class="modal-body"> 
    <%= f.hidden_field :id, value: user.id.nil? ? 0 : user.id %>
    <%= f.hidden_field :authenticity_token, value: form_authenticity_token, id: "user_authenticity_token" %>
    <% if user.id == current_user.id %>
      <%= f.hidden_field :edit_profile, value: true %>
    <% end %>
    <div class="form-group">
      <%= f.label :name %>: 
      <%= f.text_field :name, type:"text", class:"form-control", required: true, maxlength: 50 %>
    </div>
    <div class="form-group">
      <label for="picture-uploader">Picture:</label>
      <div class="custom-file" id="picture-uploader">
        <%= f.file_field :picture, class: "custom-file-input", accept: 'image/png,image/jpeg' %>
        <label for="custom-file" class="custom-file-label">Choose Image (jpeg/png format only)</label>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email %>: 
      <%= f.text_field :email, type:"email", class:"form-control", required: true, maxlength: 50, aria: { "describedby" => "emailHelp"} %>
      <small id="emailHelp" class="form-text text-danger"></small>
    </div>
    <% if policy(:application).show? && !edit_flag %>
      <div class="form-group">
        <%= f.label :role %>: 
        <%= f.select(:role, User.roles.map {|key, value|  [key.titleize,key] }, { include_blank: 'Choose...' }, { class: "selectpicker form-control", required: true }) %>
      </div>
      <div class="form-group">
        <%= f.label :password %>: 
        <%= f.text_field :password, type:"password", class:"form-control", required: true, maxlength: 50 %>
      </div>
    <% else %>
      <% if user.id == current_user.id %>
        <div class="form-group">
          <%= f.label :current_password, "Current Password" %>: 
          <%= f.text_field :current_password, type:"password", class:"form-control", required: !edit_flag, aria: { "describedby" => "currentPasswordHelp"}, maxlength: 50%>
          <small id="currentPasswordHelp" class="form-text text-danger"></small>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :password, "New Password" %>: 
        <%= f.text_field :password, type:"password", class:"form-control", required: !edit_flag, disabled: user.id.eql?(current_user.id), minlength: User.password_length.min, maxlength: 50 %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :password_confirmation %>: 
      <%= f.text_field :password_confirmation, type:"password", class:"form-control", required: !edit_flag, aria: { "describedby" => "confirmPasswordHelp"}, disabled: true, minlength: User.password_length.min, maxlength: 50 %>
      <small id="confirmPasswordHelp" class="form-text text-danger"></small>
    </div>
    <div class="form-group">
      <label for="mapContainer">Location:</label>
      <% if policy(:application).show? && !edit_flag %>
        <div style="width: 460px; height: 360px" id="mapContainer" long="121.02" lat="14.5575"></div>
      <% else %> 
        <div style="width: 460px; height: 360px" id="mapContainer" long=<%= user.longitude %> lat=<%= user.latitude %>></div>
      <% end %>
      <%= f.hidden_field :longitude %>
      <%= f.hidden_field :latitude %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" id="close" data-dismiss="modal"><%= t('close') %></button>
    <%= f.submit t('submit'), class:"btn btn-primary"%>
  </div>
<% end %>

app/views/users/_user.html.erb
<% users.each do |user| %>
  <div class="card text-white bg-info m-4" id="user-card">
    <div class="card-header">
      <%= image_tag user.picture.url(:small), class: "card-image" %>
      <% if user.name.length > 18 %>
        <a data-toggle="tooltip" data-placement="top" title='<%= user.name %>' >
          <%= user.name[0,16]+"..." %>
        </a>
      <% else %>
        <%= user.name %>
      <% end %>
      <% if user.id != current_user.id %>
        <div class="btn-group dropright" id="options">
          <button type="button"  class="btn btn-outline-info btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white;">
            :
          </button>
          <div class="dropdown-menu" >
            <% if user.user? %>
              <%= link_to t('.show_answers') , summary_path(user_id: user.id), :class => "dropdown-item"%>
              <div class="dropdown-divider"></div>
            <% end %>
            <%= link_to t('edit') , edit_user_path(user.id), :class => "dropdown-item", remote: true %>
            <%= link_to t('remove') , user_path(user.id), :method => :delete, :class => "dropdown-item", :data => {:confirm => "Remove this user?"}, remote: true %>
          </div>
        </div>
      <% end %>
    </div> 
    <div class="card-body">
      <h4>
        <%= t('.role') %> : 
        <span class="badge badge-pill badge-dark">
          &nbsp;
          <%= user.role.titleize%>
          &nbsp;
        </span>
      </h4>
      <h4>
        Email : 
        <span class="badge badge-pill badge-dark">
          &nbsp;
          <% if user.email.length > 20 %>
            <a data-toggle="tooltip" data-placement="top" title='<%= user.email %>' >
              <%= user.email[0,18]+"..." %>
            </a>
          <% else %>
            <%= user.email %>
          <% end %>
          &nbsp;
        </span>
      </h4>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('.edit_user') %></h1>

<%= render partial: 'form', locals: {user: @user, edit_flag: true} %>

app/views/users/edit.js.erb
$("#edit-modal-content").html("<%= j render partial: 'form', locals: {user: @user, edit_flag: true} %>");
$('#editUser').modal('show');

app/views/users/index.html.erb
<div class="button-container">
  <button type="button" class="btn btn-outline-primary btn-lg w-25 mx-auto" data-toggle="modal" data-target="#addUser"><%= t('.add_user')%></button> 
</div>

<div class="main-container">
  <%= render 'user', users: getter_users() %>
</div>

<div class="paginator">
  <%= paginate getter_users(), :remote => true %>
</div>

<div class="modal fade" id="addUser" tabindex="-1" role="dialog" aria-labelledby="addUserTitle" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= t('.add_user')%>
        </h5>
      </div>
        <%= render partial: 'form', locals: {user: User.new, edit_flag: false} %>
    </div>
  </div>
</div>

<div class="modal fade" id="editUser" tabindex="-1" role="dialog" aria-labelledby="editUserTitle" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">
          <%= t('.edit_user')%>
        </h5>
      </div>
      <div id="edit-modal-content"></div>
    </div>
  </div>
</div>

app/views/users/index.js.erb
$('.main-container').html('<%= escape_javascript render(partial: "user", locals: {users: getter_users()}) %>');

$('.paginator').html('<%= escape_javascript(paginate(getter_users(), :remote => true).to_s) %>');

$('[data-toggle="tooltip"]').tooltip()

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<div class="profile" >
  <div class="profile-header">
    <%= image_tag current_user.picture.url(:medium), class: "profile-picture" %>
    <div class="profile-texts">
      <h2>
        <%= current_user.name %>
      </h2>
      <h3>Account Role: <%= current_user.role.titleize %></h3>
      <h3 class="text-muted">Member since <%= current_user.created_at.localtime.to_s[0,10] %></h3>
      <%= link_to  t('.edit_profile'),  "#", { class: "btn btn-primary", "data-toggle" => "modal", "data-target" => "#editProfile"}%>
    </div>
    <div class="profile-location">
      <h2>Location: </h2>
      <%= image_tag  "https://image.maps.api.here.com/mia/1.6/mapview?app_id=#{ENV["APP_ID"]}&app_code=#{ENV["APP_CODE"]}&ctr=#{current_user.latitude},#{current_user.longitude}&poi=#{current_user.latitude},#{current_user.longitude}&z=15&poithm=1&w=360&h=280
      ", alt: "Map" %> 
      <h4 class="text-muted">
        <%= current_user.latitude.round(4).abs.to_s+"° "%><%= current_user.latitude > 0 ? 'N': 'S'%>
        <%=", "+current_user.longitude.round(4).abs.to_s+"° " %><%= current_user.longitude > 0 ? 'E': 'W'%>
      </h4>
    </div>
  </div>
</div>

<% if user_signed_in? %> 
  <div class="modal fade" id="editProfile" tabindex="-1" role="dialog" aria-labelledby="editProfileTitle" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog" role="document">
      <div class="modal-content" id="edit-modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">
            <%= t('.edit_profile')%>
          </h5>
        </div>
        <%= render partial: 'form', locals: { user: current_user, edit_flag: true} %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>