config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :answers
      resources :equipment
      resources :questions

      root to: 'users#index'
    end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :answers, except: %i[show new]
  resources :equipment, except: :show
  resources :questions, except: :show do
    get 'summary', as: 'summary'
  end

  resources :users, except: :show

  root to: 'home#index', as: 'home'

  get 'summary', as: 'summary', controller: :answers, action: :index
  put 'validate', as: 'validate', controller: :users
  get 'profile', as: 'profile', controller: :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Officeman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-ui.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js"></script>
    <link rel="stylesheet" type="text/css" href="https://js.api.here.com/v3/3.1/mapsjs-ui.css" />
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark" id="nav-color">
        <%= link_to(home_path,class: "navbar-brand") do%>
          <%= inline_svg "officeman_logo.svg", height: "40" %>
        <% end %>
        <% if user_signed_in? %> 
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to t('.home'), home_path, class: "nav-link" %>
            </li>
            <% if policy(:application).show? %>
              <li class="nav-item">
                <%= link_to t('.user'), users_path, class: "nav-link" %>
            </li>
            <% end %>
            <li class="nav-item">
              <%= link_to t('.question'), questions_path,class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to t('.equipment'), equipment_index_path,class: "nav-link" %>
            </li>
            <li class="nav-item">
              <div class="dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">
                  <% if current_user.name.length > 17 %>
                    <%= current_user.name[0,15]+"..." %>
                  <% else %>
                    <%= current_user.name %>
                  <% end%>
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <%= link_to t('.profile'), profile_path, class: "dropdown-item" %>
                  <% if policy(:application).show? %>
                    <%= link_to t('.dashboard'), admin_root_path, class: "dropdown-item" %>
                  <% end %>
                  <div class="dropdown-divider"></div>
                  <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              </div>
            </li>
          </ul>
        <% elsif request.env['PATH_INFO'].eql? home_path %>
          <div class="w-75 text-right">
            <%= button_to t('.login'), new_user_session_path, method: :get, class: "btn btn-outline-light", id: "login" %>
          </div>
        <% end %>
      </nav>
    </header> 
    <main class='<%= controller.controller_name %>'>
      <% if notice %>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>